package edu.wpi.teamname.services.database.requests;

public enum RequestType {
  AUDIO_VISUAL,
  COMPUTER_SERVICE,
  EXTERNAL_PATIENT_TRANSPORTATION,
  FLORAL,
  FOOD_DELIVERY,
  GIFT_DELIVERY,
  INTERNAL_PATIENT_TRANSPORTATION,
  LANGUAGE_INTERPRETER,
  LAUNDRY,
  MAINTENANCE,
  MEDICINE_DELIVERY,
  RELIGIOUS,
  SANITATION,
  SECURITY
}
